name: Terraform Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7 

    - name: Configure AWS Credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

    - name: List files in terraform directory
      run: ls -al terraform

    - name: terraform init
      run: terraform init
      working-directory: terraform

    - name: terraform validate
      run: terraform validate
      working-directory: terraform

    - name: terraform plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: terraform

    - name: terraform apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
      working-directory: terraform

    - name: terraform output
      run: terraform output
      working-directory: terraform
